### PR TITLE
Update setup.sh

### PR DESCRIPTION
**Pull request by jukka413**
You need to return previos version. Becose with python3.9 your envyroment in the Lab is not working. No venv. No such python version as 3.9 there

### CODE REVIEW

**Comment by rofrano** [comment]
@jukka413 I'm getting the same failure but I noticed that the lab environment was using the outdated Ubuntu 18.04 environment. I'm checking to see if the course link needs to be updated to use the new Ubuntu 22.04 environment. I will report back here.

**Comment by jukka413** [comment]
I'm take the course, thank you for it. I notice that there different python versions in different parts, but previous version of setup.sh works everywhere. 
Thank you for your answer

**Comment by rofrano** [comment]
@jukka413 When you are in a lab that doesn't work, can you run this command and post the output here.

```bash
cat /etc/os-release 
```

Also let me know which Week and which Lab. Thanks

**Comment by jukka413** [comment]
@rofrano 
```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

It was week 2, lab "Hands-On Lab: Develop a RESTful Service Using Test Driven Development (TDD)".
There was python3.8 as latest version when was error.
Now there python3.10 and current file "setup.sh" working well.
Thank you for your time.

**Comment by rofrano** [comment]
@jukka413 Thanks for the info. I think we have them all launching the correct environment now.

**Pull request closed without merging**
